#!/bin/bash 
#PBS -N Prep_SKIRT9
#PBS -o /home/connor.bottrell/Scratch/pbs
#PBS -e /home/connor.bottrell/Scratch/pbs
#PBS -l select=1:ncpus=1:mem=64gb
#PBS -l walltime=72:0:0
#PBS -J 0-3500:1
#PBS -u bottrell
#PBS -M connor.bottrell@ipmu.jp
#PBS -m ae
#PBS -V
#PBS -q tiny

conda activate tf39_cpu

export SNAP=91

cd /lustre/work/connor.bottrell/Simulations/IllustrisTNG/Scripts/SKIRT

python Prepare_SKIRT.py $SNAP $PBS_ARRAY_INDEX

